/**
 * The emitters: a resolved tree in, the source of a manifest module and a per-target entry
 * point out.
 *
 * They return strings rather than writing files, so what a build produces can be asserted on
 * without a temp directory, and so the only code that touches the disk is `build.ts`.
 *
 * What comes out is a static module. No directory is read, no path is resolved and no Markdown
 * file is opened at runtime, because the target has none of those — instructions and skills are
 * inlined as string literals and every entry point becomes an `import` (ADR-0001).
 */
import type { AgentTree } from './loader'
import path from 'node:path'
import { AgentTreeError } from './loader'

/** The platforms a generated entry point is shaped for. */
export const BUILD_TARGETS = ['cloudflare', 'vercel'] as const
export type BuildTarget = typeof BUILD_TARGETS[number]

/** The name the manifest module is written under, and what an entry point imports. */
export const MANIFEST_MODULE = 'manifest.ts'

const HEADER = `/* eslint-disable */
// Generated by \`amond build\`. Do not edit — change \`agent/\` and build again.`

/** A resolved file and the identifier the generated module binds its default export to. */
interface Binding {
  readonly binding: string
  readonly file: string
}

/**
 * Emit the manifest module: every resolved file as a static import, every Markdown file as a
 * string literal.
 *
 * `outDir` is where the module will be written, because that is what its relative import
 * specifiers resolve against.
 */
export function emitManifestModule(tree: AgentTree, outDir: string): string {
  if (tree.config === undefined) {
    throw new AgentTreeError(
      path.join(tree.root, 'agent.ts'),
      'missing — a manifest needs a harness, and the harness is chosen here (ADR-0001)',
    )
  }

  const tools = bind('tool', tree.tools)
  const schedules = bind('schedule', tree.schedules)
  const channels = bind('channel', tree.channels)

  const imports = [...tools, ...schedules, ...channels]
    .map(({ binding, file }) => `import ${binding} from ${literal(specifier(outDir, file))}`)

  const skills = tree.skills
    .map(skill => `    { name: ${literal(skill.name)}, instructions: ${literal(skill.instructions)} },`)

  return `${[
    HEADER,
    '//',
    `// The tree at ${tree.root}, resolved.`,
    `import type { AgentConfig, AgentManifest } from '@amond-ai/agent-core'`,
    `import config from ${literal(specifier(outDir, tree.config))}`,
    ...imports,
    '',
    '// Named here rather than inlined below, so a config missing its harness fails against',
    '// `agent.ts` instead of somewhere inside a generated object literal.',
    'const agentConfig: AgentConfig = config',
    '',
    'export const manifest: AgentManifest = {',
    `  instructions: ${literal(tree.instructions)},`,
    `  tools: [${list(tools)}],`,
    `  skills: [${skills.length > 0 ? `\n${skills.join('\n')}\n  ` : ''}],`,
    `  schedules: [${list(schedules)}],`,
    `  channels: [${list(channels)}],`,
    '  harness: agentConfig.harness,',
    '}',
  ].join('\n')}\n`
}

const CLOUDFLARE_ENTRY = `/**
 * The Worker's module entry: point \`main\` in your \`wrangler.jsonc\` at this file, and declare
 * the triggers there.
 */
export default {
  fetch: (request: Request) => handlers.fetch(request),
  // Typed structurally rather than as \`ScheduledController\`, so this entry point typechecks
  // in a project that has not installed \`@cloudflare/workers-types\`.
  scheduled: (controller: { readonly scheduledTime: number }) =>
    handlers.scheduled(new Date(controller.scheduledTime)),
}
`

const VERCEL_ENTRY = `/**
 * A route handler: re-export it from a route in your app, and point \`vercel.json\`'s cron at
 * that same path. On Vercel a schedule arrives as an HTTP request, so \`GET\` is the cron entry
 * and \`POST\` carries channel events.
 */
export const POST = (request: Request) => handlers.fetch(request)

export async function GET(): Promise<Response> {
  await handlers.scheduled(new Date())
  return new Response(null, { status: 204 })
}
`

/**
 * Emit the entry point a platform invokes: it builds the handlers from the manifest and
 * re-exports them in the shape that platform expects.
 *
 * The wiring around it stays the user's — `wrangler.jsonc`, `vercel.json` and cron
 * registration are not generated, so a framework release cannot silently rewrite a deploy.
 */
export function emitEntryPoint(target: BuildTarget): string {
  return `${HEADER}
import { createHandlers } from '@amond-ai/agent-core'
import { manifest } from './${MANIFEST_MODULE}'

const handlers = createHandlers(manifest)

${target === 'cloudflare' ? CLOUDFLARE_ENTRY : VERCEL_ENTRY}`
}

/**
 * Bind each file to an identifier derived from its kind and position rather than its name:
 * `search-issues.ts` and `search_issues.ts` would collide on any name-derived identifier, and
 * the import's own specifier already says which file the binding came from.
 */
function bind(kind: 'tool' | 'schedule' | 'channel', files: readonly string[]): Binding[] {
  return files.map((file, index) => ({ binding: `${kind}${index}`, file }))
}

function list(bindings: readonly Binding[]): string {
  return bindings.map(({ binding }) => binding).join(', ')
}

/** A string the generated module can carry verbatim, escapes and all. */
function literal(value: string): string {
  return JSON.stringify(value)
}

/**
 * A relative, POSIX-separated import specifier — what a bundler and Bun both resolve.
 *
 * Emitted through `literal`, never interpolated into quotes of our own: a filename is allowed an
 * apostrophe, and one would otherwise close the string and leave a module that cannot be parsed.
 */
function specifier(from: string, to: string): string {
  const relative = path.relative(from, to).split(path.sep).join('/')
  return relative.startsWith('.') ? relative : `./${relative}`
}
